version: "3"
services:
  web:
    build:
      context: ../
      dockerfile: Dockerfile
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - type: bind
        source: "./nginx_default.conf"
        target: "/etc/nginx/conf.d/default.conf"
      - type: bind
        source: "./letsencrypt"
        target: "/etc/letsencrypt"
      - type: bind
        source: "./www"
        target: "/var/www"

